#!/bin/bash

service_address=$(curl -s localhost:9000/api/v1/instances/test | jq -r .\"services\".\"test-ui\".\"address\")
service_port=$(curl -s localhost:9000/api/v1/instances/test | jq -r .\"services\".\"test-ui\".\"port\")
service_socket=$service_address:$service_port

curl -s $service_socket > /dev/null
