#!/bin/bash
docker run -d --net host frosner/cluster-broccoli-test nomad > nomad.did
sleep $BROCCOLI_SLEEP_MEDIUM
docker run -d --net host frosner/cluster-broccoli-test cluster-broccoli > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
