#!/bin/bash

set -e

rm -rf cluster-broccoli-*
rm -rf docker/test/cluster-broccoli-dist
sbt clean && sbt dist
unzip server/target/universal/cluster-broccoli*.zip
cp -R cluster-broccoli-* docker/test/cluster-broccoli-dist
cp -R templates docker/test/
rm -rf cluster-broccoli-*

if [ -z "$BROCCOLI_SLEEP_LONG" ]; then
  export BROCCOLI_SLEEP_LONG=10
fi
echo '$BROCCOLI_SLEEP_LONG'="$BROCCOLI_SLEEP_LONG"

if [ -z "$BROCCOLI_SLEEP_MEDIUM" ]; then
  export BROCCOLI_SLEEP_MEDIUM=3
fi
echo '$BROCCOLI_SLEEP_MEDIUM'="$BROCCOLI_SLEEP_MEDIUM"

if [ -z "$BROCCOLI_SLEEP_SHORT" ]; then
  export BROCCOLI_SLEEP_SHORT=1
fi
echo '$BROCCOLI_SLEEP_SHORT'="$BROCCOLI_SLEEP_SHORT"

set +e

