#!/bin/bash

curl -H 'Content-Type: application/json' \
  -X POST -d '{ "templateId": "http-server", "parameters": { "id": "test-http", "cpu": 250 } }' \
  'http://localhost:9000/api/v1/instances'
sleep $BROCCOLI_SLEEP_SHORT
docker stop $(cat cluster-broccoli.did)
sleep $BROCCOLI_SLEEP_SHORT
docker run --rm -d --net host \
  frosner/cluster-broccoli-test \
  cluster-broccoli \
  -Dconfig.file=/couchdb.conf > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
curl -s localhost:9000 > /dev/null && echo "Broccoli started successfully" || echo "Broccoli did not start, yet"
