#!/bin/bash
curl -H 'Content-Type: application/json' \
  -X POST -d '{ "templateId": "http-server", "parameters": { "id": "test-http", "cpu": 250 } }' \
  'http://localhost:9000/api/v1/instances'
sleep $BROCCOLI_SLEEP_SHORT
curl -v -H 'Content-Type: application/json' \
  -X POST -d '{ "parameterValues": { "id": "test-http", "cpu": 50 } }' \
  'http://localhost:9000/api/v1/instances/test-http'
sleep $BROCCOLI_SLEEP_SHORT
docker stop $(cat cluster-broccoli.did)
sleep $BROCCOLI_SLEEP_SHORT
docker run --rm -d --net host \
  -v /tmp/instances:/cluster-broccoli-dist/instances \
  frosner/cluster-broccoli-test \
  cluster-broccoli > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
