#!/bin/bash
curl -H 'Content-Type: application/json' \
  -X POST -d '{ "templateId": "http-server", "parameters": { "id": "test-http", "cpu": "250" } }' \
  'http://localhost:9000/api/v1/instances'
sleep 2
curl -v -H 'Content-Type: application/json' \
  -X POST -d '{ "parameterValues": { "id": "test-http", "cpu": "50" } }' \
  'http://localhost:9000/api/v1/instances/test-http'
sleep 1
docker stop $(cat cluster-broccoli.did)
sleep 1
docker run -d --net host frosner/cluster-broccoli-test \
  -v /tmp/instances:/instances
  /cluster-broccoli-dist/bin/cluster-broccoli \
  -Dbroccoli.templatesDir=/templates \
  -Dbroccoli.instancesDir=/instances > cluster-broccoli.did
sleep 5
