#!/bin/bash

echo "Printing nomad logs"
docker logs $(cat nomad.did)
echo "Printing consul logs"
docker logs $(cat consul.did)
docker stop $(cat cluster-broccoli.did)
docker stop $(cat nomad.did)
docker stop $(cat consul.did)
