#!/bin/bash
docker run -d --net host frosner/cluster-broccoli-test cluster-broccoli > cluster-broccoli.did
sleep 5
docker run -d --net host -v /var/run/docker.sock:/var/run/docker.sock frosner/cluster-broccoli-test nomad > nomad.did
sleep 5
docker run -d --net host frosner/cluster-broccoli-test consul > consul.did
sleep 5
