#!/bin/bash
docker run -d --net host frosner/cluster-broccoli-test cluster-broccoli > cluster-broccoli.did
docker run -d --net host frosner/cluster-broccoli-test nomad > nomad.did
docker run -d --net host frosner/cluster-broccoli-test consul > consul.did
sleep 10
