#!/bin/bash
source $(dirname "$0")/../common.sh
docker run --rm -d --net host frosner/cluster-broccoli-test cluster-broccoli > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
check_service http localhost 9000
