#!/bin/bash
docker run -d --net host frosner/cluster-broccoli-test \
  /cluster-broccoli-dist/bin/cluster-broccoli -Dbroccoli.permissions.mode=operator > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
