#!/bin/bash

for i in $(seq 1 500)
do
  curl -s -H 'Content-Type: application/json' \
    -X POST -d "{ \"templateId\": \"http-server\", \"parameters\": { \"id\": \"test-http-$i\", \"cpu\": 250 } }" \
    'http://localhost:9000/api/v1/instances' > /dev/null
done
sleep $BROCCOLI_SLEEP_SHORT
docker stop $(cat cluster-broccoli.did)
sleep $BROCCOLI_SLEEP_SHORT
docker run --rm -d --net host \
  -v /tmp/instances:/cluster-broccoli-dist/instances \
  frosner/cluster-broccoli-test \
  cluster-broccoli > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
