#!/bin/bash

service_address=$(curl -s localhost:9000/api/v1/instances/test | jq -r '."services" | map(select(."name" == "test-web-ui-1"))[0]."address"')
service_port=$(curl -s localhost:9000/api/v1/instances/test | jq -r '."services" | map(select(."name" == "test-web-ui-1"))[0]."port"')
service_socket=$service_address:$service_port

echo "      - Waiting for service $service_socket to come up ..."
curl -s $service_socket > /dev/null
