#!/bin/bash
docker run -d --net host \
  frosner/cluster-broccoli-test \
  cluster-broccoli \
  -Dbroccoli.instances.storage.type=couchdb > cluster-broccoli.did

docker pull couchdb
docker run -d --net host couchdb > couchdb.did

sleep $BROCCOLI_SLEEP_MEDIUM
