#!/bin/bash

instances_mount=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/instances:/instances

docker stop $(cat cluster-broccoli.did)
docker run -d --net host -v $instances_mount frosner/cluster-broccoli-test \
  /cluster-broccoli-dist/bin/cluster-broccoli \
  -Dbroccoli.permissions.mode=administrator > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM

curl -H 'Content-Type: application/json' \
  -X POST -d '{ "templateId": "http-server", "parameters": { "id": "test-http", "cpu": "250" } }' \
  'http://localhost:9000/api/v1/instances'
sleep $BROCCOLI_SLEEP_MEDIUM

docker stop $(cat cluster-broccoli.did)
docker run -d --net host -v $instances_mount frosner/cluster-broccoli-test \
  /cluster-broccoli-dist/bin/cluster-broccoli \
  -Dbroccoli.permissions.mode=operator > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
